[package]
name = "bionic"
version = "0.0.0"
edition = "2021"
description = "A machine learning library for Rust"
license = "MIT"

[dependencies]
nalgebra = "0.32.1"

[features]
default = ["glm"]
glm = []